name: Deploy Python 3.12 App to Azure Web App - ailab-webapp3-dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉代码
      - uses: actions/checkout@v4

      # 2. Python 3.12
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. 安装依赖到当前目录（关键！！！）
      - name: Install dependencies locally
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target="./.python_packages/lib/site-packages"

      # 4. 打包
      - name: Zip artifact
        run: |
          zip -r app.zip . -x "*.git*" -x "antenv/*" -x "__pycache__/*"

      # 5. 部署
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ailab-webapp3-dev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1FD94038CAFC4BC3A0D52326C915FCFC }}
          package: app.zip
